# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments

plugins: [jekyll-paginate]
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : https://rdiaz82.github.io


title : Roberto Diaz



author:
  name: Roberto Diaz
  role: Software Developer
  email: meliodus@tutanota.com
  github: meliodus
  twitter: talk2ankan
  facebook: talk2ankan
  googleplus: +AnkanBiswasWorkspace
  bio: "I'm passionate about technology and I'm always learning new things"
